### ISSUE TITLE
Second Plex server library sync always fails (NoSuchMethodError crashes LibrarySyncWorker on Android 9 / API 28)

### ISSUE THREAD

**Issue by XenaRathon** [ChakirHamzaChahid/PlexhubTV_Release#2]
## Summary

Library sync for a **second** Plex server always fails with "La synchronisation a échoué" (Retry/Exit dialog), on a multi-Plex-server account. Root cause appears to be a `NoSuchMethodError` crashing `LibrarySyncWorker` on Android 9 (API 28) devices, not a network/auth issue.

## Environment

- App version: v1.0.58 (armeabi-v7a build), installed via sideload + in-app OTA update
- Device: Amazon Fire TV Cube, 2nd gen (`AFTGAZL` / codename `gazelle`)
- OS: Fire OS 7, Android 9 (`ro.build.version.sdk=28`)
- Account setup: 1 Plex account linked via PIN login, **2 Plex servers** visible in "Choose your libraries" (own server "Xen-Flix" + a second server "MediaHUB")

## Repro steps

1. Fresh install, link Plex account via "Login with PIN".
2. Reach "Choose your libraries" — first server's libraries sync fine.
3. Switch to the second server's tab in the library picker.
4. Sync fails immediately with the red warning screen: "La synchronisation a échoué." / Retry / Exit.
5. Retry sometimes succeeds transiently (loads the second server's library list once), but confirming the selection re-triggers the same failure, and it becomes persistent — Retry no longer helps after that point.
6. Fails identically before and after updating to v1.0.58 (which fixed an unrelated multi-server home-row crash).

## Actual error (logcat)

Captured via `adb logcat` while reproducing:

```
E WM-WorkerWrapper: java.lang.NoSuchMethodError: No static method beginAsyncSection(Ljava/lang/String;I)V in class Landroid/os/Trace; or its super classes (declaration of 'android.os.Trace' appears in /system/framework/framework.jar!classes2.dex)
E WM-WorkerWrapper: 	at dj.a.w(Unknown Source:2)
E WM-WorkerWrapper: 	at com.chakir.plexhubtv.work.LibrarySyncWorker.f(Unknown Source:61)
E WM-WorkerWrapper: 	at t6.h.invokeSuspend(Unknown Source:30)
E WM-WorkerWrapper: 	at t6.h.invoke(Unknown Source:17)
E WM-WorkerWrapper: 	at ra.s0.invokeSuspend(Unknown Source:1837)
E WM-WorkerWrapper: 	at eh.a.resumeWith(Unknown Source:8)
E WM-WorkerWrapper: 	at ei.h0.run(Unknown Source:113)
E WM-WorkerWrapper: 	at mi.a.run(Unknown Source:117)
```

## Likely root cause

`android.os.Trace.beginAsyncSection(String, int)` was only added in **API 29 (Android 10)** — see the AOSP `Trace` class. This device is API 28 (Android 9), where that method does not exist in `framework.jar` at all, so calling it throws `NoSuchMethodError` rather than failing gracefully.

`LibrarySyncWorker` (via an obfuscated tracing helper, `dj.a`, likely a wrapper around `androidx.tracing`/WorkManager's built-in tracing instrumentation) appears to call this unconditionally, with no `Build.VERSION.SDK_INT >= 29` guard. That crashes the worker before it does any real sync work, on every attempt, on any Android 9 device — which would explain why this wasn't caught by the v1.0.58 test campaign's "22 servers, 50 rows" validation if no Android 9 device was in that matrix.

## Suggested fix

Guard the trace call with an SDK check (e.g. `if (Build.VERSION.SDK_INT >= 29) Trace.beginAsyncSection(...)`), or use `androidx.tracing.Trace` (the AndroidX compat wrapper) instead of the raw platform API if not already doing so — it back-fills this exact gap on older API levels.

Happy to provide the full logcat capture or test a patched build on this device (2nd-gen Fire TV Cube) if useful.

**Comment by XenaRathon** [comment]
**Update: this is NOT multi-server-specific — please broaden the scope.**

Re-tested with only the single "Xen-Flix" server connected (removed the second server entirely) and got the exact same failure — identical crash, same line numbers, same worker ID pattern:

```
E WM-WorkerWrapper: Work [ id=016d7543-25c4-4202-b317-fe591f853226, tags={ com.chakir.plexhubtv.work.LibrarySyncWorker } ] failed because it threw an exception/error
E WM-WorkerWrapper: java.lang.NoSuchMethodError: No static method beginAsyncSection(Ljava/lang/String;I)V in class Landroid/os/Trace; or its super classes (declaration of 'android.os.Trace' appears in /system/framework/framework.jar!classes2.dex)
E WM-WorkerWrapper: 	at dj.a.w(Unknown Source:2)
E WM-WorkerWrapper: 	at com.chakir.plexhubtv.work.LibrarySyncWorker.f(Unknown Source:61)
E WM-WorkerWrapper: 	at t6.h.invokeSuspend(Unknown Source:30)
E WM-WorkerWrapper: 	at t6.h.invoke(Unknown Source:17)
E WM-WorkerWrapper: 	at ra.s0.invokeSuspend(Unknown Source:1837)
E WM-WorkerWrapper: 	at eh.a.resumeWith(Unknown Source:8)
E WM-WorkerWrapper: 	at ei.h0.run(Unknown Source:113)
E WM-WorkerWrapper: 	at mi.a.run(Unknown Source:117)
```

So the actual bug is: **`LibrarySyncWorker` crashes on its first `Trace.beginAsyncSection` call on any Android 9 / API 28 device, regardless of server count.** Library sync cannot complete at all on this class of device (2nd-gen Fire TV Cube / Fire OS 7, and presumably any other Android-9 Android TV box) — it's not an edge case limited to multi-Plex-server accounts. Single-server users on API 28 hardware would hit this on their very first sync.

Given it's unconditional on API level rather than server count, this seems like it'd reproduce on an emulator/AVD running API 28 with a single test Plex server — should be straightforward to confirm without needing multi-server test infrastructure.

**Comment by XenaRathon** [comment]
**Correction: device generation.**

I misidentified the device generation earlier — `AFTGAZL` ("gazelle") is the **3rd-generation** Fire TV Cube, not 2nd-gen. Correcting for anyone triaging: this bug is on Amazon's **current, still-sold** Fire TV Cube, not a discontinued unit — worth weighting the severity accordingly.

The actual technical facts are unaffected by this correction and were pulled directly from the device via `adb shell getprop`, not inferred from the model name:
- `ro.build.version.release` = 9
- `ro.build.version.sdk` = 28

So: 3rd-gen Fire TV Cube, shipping Fire OS 7 / Android 9 (API 28), and library sync cannot complete on it at all in the current build.
